name: Experimental Build and Deploy to Production
on:
  push:
    branches:
      - feature/**

jobs:
  build-java:
    name: Build and Push Java Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build with Gradle
        working-directory: ./microsservicos/checkout
        run: ./gradlew bootJar
      - name: List Build Artifacts
        working-directory: ./microsservicos/checkout
        run: ls -la build/libs/
