name: Experimental Build and Deploy

on:
  push:
    branches:
      - feature/**

jobs:
  build-java:
    name: Build and Push Java Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set Gradle Wrapper Permissions
        working-directory: ./microsservicos/checkout
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./microsservicos/checkout
        run: ./gradlew bootJar

      - name: List Build Artifacts
        working-directory: ./microsservicos/checkout
        run: ls -la build/libs/

      - name: Authenticate to Google Cloud
        id: auth
        uses: "google-github-actions/auth@v3"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: access_token
          service_account: "deploy@cp5java.iam.gserviceaccount.com"

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: southamerica-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./microsservicos/checkout
          push: true
          tags: southamerica-east1-docker.pkg.dev/cp5java/cp5repo/ms-checkout:latest
